### ISSUE TITLE
SQL syntax error on introspect

### ISSUE THREAD

**Issue by nubenum** [RichardKnop/go-oauth2-server#37] opened 2017-10-08 10:21 UTC
On trying to do an introspect on an access_token, I'm seeing the following error in the log:

```
[2017-10-08 09:56:55]  [1.20ms]  SELECT * FROM "oauth_access_tokens"  WHERE "oauth_access_tokens"."deleted_at" IS NULL AND ((token = '925c405b-b593-48c9-bc4e-48962d3e0401')) ORDER BY "oauth_access_tokens"."id" ASC LIMIT 1

(/go/src/github.com/RichardKnop/go-oauth2-server/oauth/authenticate.go:45) 
[2017-10-08 09:56:55]  [0.60ms]  UPDATE "oauth_refresh_tokens" SET "expires_at" = '2017-10-22 09:56:55'  WHERE "oauth_refresh_tokens"."deleted_at" IS NULL AND ((client_id = '1') AND (user_id = 'bdeb6242-e6b1-4799-bfee-3b0e7458083a'))

(/go/src/github.com/RichardKnop/go-oauth2-server/oauth/introspect.go:74) 
[2017-10-08 09:56:55]  [0.55ms]  SELECT key FROM "oauth_clients"  WHERE "oauth_clients"."deleted_at" IS NULL AND (("oauth_clients"."id" = '1')) ORDER BY "oauth_clients"."id" ASC LIMIT 1

(/go/src/github.com/RichardKnop/go-oauth2-server/oauth/introspect.go:84) 
[2017-10-08 09:56:55]  pq: syntax error at or near "b0e7458083a" 

(/go/src/github.com/RichardKnop/go-oauth2-server/oauth/introspect.go:84) 
[2017-10-08 09:56:55]  [0.47ms]  SELECT username FROM "oauth_users"  WHERE "oauth_users"."deleted_at" IS NULL AND ((bdeb6242-e6b1-4799-bfee-3b0e7458083a)) ORDER BY "oauth_users"."id" ASC LIMIT 1
[negroni] 2017-10-08T09:56:55Z | 200 |   104.117984ms | go_oauth2_server:8080 | POST /v1/oauth/introspect 
```
So, everything but the username I am actually interested in is returned to the OAuth client. I use the docker container, but maybe I'm still just getting something wrong.

By the way, in the documentation on line 126, it says that in the authorization_code grant response with the access_token, the server also returns a user_id (that may be persistent also after requesting a new access_token?). However, I'm never actually seeing this user_id being returned.

Thanks a lot for your efforts.

**Comment by RichardKnop** [comment] 2017-10-10 16:45
So the error seems to be happening on this line: https://github.com/RichardKnop/go-oauth2-server/blob/master/oauth/introspect.go#L84

I wonder what the issue is there. I guess the user ID is empty? But it shouldn't go inside the if condition if it's empty.

The access token response should also contain "user_id" field if the access token is related to a user (obviously access token generated for client won't have `user_id`).

EDIT: I have actually looked at the codebase and found some small issues. There was `oauth_users.meta_user_id` field still in the user model. I removed it (it was used for something before but is not used anymore). Also fixed initialization of access token responses to handle user ID correctly.

Git pull & let me know if this issue still exists in the latest commit.

**Comment by nubenum** [comment] 2017-10-10 21:23
Ok so your changes fixed the issue with the user_id which is now correctly returned in the access_token response. However, the introspect still failed with the same SQL Syntax error in this statement:
```
SELECT username FROM "oauth_users"  WHERE "oauth_users"."deleted_at" IS NULL AND ((bdeb6242-e6b1-4799-bfee-3b0e7458083a)) ORDER BY "oauth_users"."id" ASC LIMIT 1
```
The SQL would be easy to fix, as it just needs to be 
```
(("oauth_users"."id" = "bdeb6242-e6b1-4799-bfee-3b0e7458083a"))
```
However, I was not able to track down where and why the SQL statement is not properly assembled. My testing showed that it would fail as soon as one passes a string that is not an integer, i.e. that does not consist of nothing but numbers. The ClientID is integer, the UserID being a UUID obviously not (although both are treated as text in the DB). Maybe it is even an upstream bug in jinzhu's gorm lib.

In any case, it worked by just replacing lines 84 and 116 (`s.db.Select("username").First(user, refreshToken.UserID.String)`) to use the following command respectively:
```
s.db.Select("username").Where("id = ?", accessToken.UserID.String).First(user)
s.db.Select("username").Where("id = ?", refreshToken.UserID.String).First(user)
```
So, as far as I am concerned, the issue is resolved. I can send you a pull request for these two lines if you want.

**Comment by RichardKnop** [comment] 2017-10-10 23:04
@nubenum Thanks, the where condition in that query seems to be broken indeed. If you could send a PR that would be great.

**Comment by RichardKnop** [comment] 2017-10-11 11:28
@nubenum Should be fixed now. Also refactored tests to run via docker-compose.

**Comment by RichardKnop** [comment] 2017-10-11 18:20
@nubenum Agreed. There might be other bugs with SQL. But in my defense the introspect functionality was submitted as a PR by somebody else. Most of other oauth2 functionality was written by me so hopefully my tests are solid enough to catch anything. 

Also this has been used in production and seems to work well (we haven’t used introspect endpoint so haven’t found this issue).

I have updated dependencies in vendor folder with dep ensure -update. Might have been why you needed to rebuild.

**Comment by nubenum** [comment] 2017-10-12 15:35
This was certainly not a hint that it is your responsibility, it may well be that the bug is actually in the DB library. I just wasn't able to pin it down.
Anyways, thanks a lot for your work!

**Closed** 2017-10-12 16:07 UTC
